version: '3.8'

services:
  my_website:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "serve", "--livereload", "--port=8080", "--host=0.0.0.0" ]
    ports:
      - "8080:8080"
      - "35729:35729"