version: '3.8'

services:
  my_website:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "serve", "--watch", "--port=8080", "--host=0.0.0.0" ]
    volumes:
      - .:/srv/jekyll/
    ports:
      - "8080:8080"